package main

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/coder/guts"
	"github.com/coder/guts/config"
)

func generateTypeScriptCode(dir string, outputDir string) error {
	// Step 1: Create a new Golang parser
	golang, err := guts.NewGolangParser()
	if err != nil {
		return err
	}

	golang.IncludeGenerate(dir)
	ts, err := golang.ToTypescript()
	if err != nil {
		return err
	}

	ts.ApplyMutations(
		config.ExportTypes, // add 'export' to all top level declarations
	)

	output, err := ts.Serialize()
	if err != nil {
		return err
	}
	output = strings.ReplaceAll(output, "// Code generated by 'guts'. DO NOT EDIT.", "")

	if outputDir != "" {
		err := os.Mkdir(filepath.Join(outputDir), 0o775)
		if err != nil {
			if !errors.Is(err, os.ErrExist) {
				return err
			}
		}
		err = os.WriteFile(filepath.Join(outputDir, "geneveev_generated.ts"), []byte(output), os.FileMode(0o777))
		if err != nil {
			return err
		}
		return nil
	}

	fmt.Println(output)
	return nil
}
